### ISSUE TITLE
Additional optional dependency: KF5Baloo

### ISSUE THREAD

**Issue by Siosm** [flathub/org.kde.gwenview#1]
From https://github.com/flathub/flathub/pull/1583#issuecomment-719780299:

> -- The following OPTIONAL packages have not been found:
> 
> * CFitsio, FITS format support, https://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
> * KF5Kipi, Provides various image manipulation and export features, https://phabricator.kde.org/source/kipi-plugins/
> * KF5Baloo (required version >= 5.1.90), Desktop-wide semantic information support, https://commits.kde.org/baloo
> * KF5KDcraw, C++ interface around LibRaw library used to decode RAW picture files, https://phabricator.kde.org/source/libkdcraw/

**Comment by travier** [comment]
Since https://github.com/flathub/org.kde.gwenview/pull/3, only KF5Baloo is missing.
