### ISSUE TITLE
Videos are not working correctly

### ISSUE THREAD

**Issue by Dannniello** [flathub/org.kde.gwenview#10]
Hello,

Videos on flatpak version of Gwenview are displayed as pixelated slideshows without sound. Probably it could be related to missing `dragon` player...

Best Regards,
Daniel

**Comment by i-need-to-tell-you-something** [comment]
I don't have the dragon player flatpak or apt packages.

For me, the videos play normally, except there was no sound. That was fixed by using Flatseal to add the `socket=pulseaudio` permission to the Gwenview flatpak.

**Comment by Dannniello** [comment]
True - I checked newest flatpak org.kde.gwenview 22.08.2 and indeed video now is working OK, but without sound.

Probably you are right that it could be fixed with third party apps by adding permissions, but sound should work by default...

**Comment by tsdgeos** [comment]
https://github.com/flathub/org.kde.gwenview/pull/51
