### ISSUE TITLE
.heif files cannot be viewed

### ISSUE THREAD

**Issue by joewood9364** [flathub/org.kde.gwenview#158]
.heif files cannot be viewed

**Comment by Erick555** [comment]
this waits fore new runtime: https://invent.kde.org/packaging/flatpak-kde-runtime/-/merge_requests/152#note_1016375

**Comment by Erick555** [comment]
it may depend on which codec was used in this videos. runtime has ffmpeg but not every codec is included.

**Comment by Erick555** [comment]
it will be fixed same time as heic

**Comment by travier** [comment]
That should be fixed with https://github.com/flathub/org.kde.gwenview/pull/164

**Comment by Erick555** [comment]
you need to add ffmpeg-full extension as well
