### ISSUE TITLE
Use existing thumbnail cache folder

### ISSUE THREAD

**Issue by johnandmegh** [flathub/org.kde.gwenview#168]
Hi - is it possible to have the Gwenview Flatpak point at the same location as the user's main thumbnail storage, `~/.cache/thumbnails`, so it doesn't have to regenerate new thumbnails for each file/folder with which it's used?

**Comment by Erick555** [comment]
Try `flatpak run --filesystem=xdg-cache/thumbnails org.kde.gwenview`

In order to make it persistent do `flatpak override --user  --filesystem=xdg-cache/thumbnails org.kde.gwenview`

This digs a hole in the sandbox so it may not an acceptable default.

**Comment by johnandmegh** [comment]
Thanks, that does work on an individual basis - I guess my thought was that this seemed like a desirable default because:

Gwenview already has `filesystem=host`, so giving it thumbnails folder access seems like it wouldn't make much of a security difference?
It would improve the situation for OSes like the future KDE Linux that depend on Flatpaks for all apps including file management, since it would enable one thumbnail cache to be shared across the different Flatpaks (especially Gwenview and Dolphin?)

I might be misunderstanding part or all of that, apologies for the wasted time if that's the case - but mostly trying to think of what the future state uses will be for this Flatpak, and it seems like a nice efficiency gain to not have to calculate and store multiple copies of the thumbnail cache.

**Comment by Erick555** [comment]
For apps that have `filesystem=host` it wouldn't make much difference but having it may not be something desired to be kept over the long run. The future goal should be having meaningful sandbox. Shared thumbnail cache for all apps would mean putting something malicious there will affect all apps at once like there was no sandbox.

**Comment by travier** [comment]
Sounds like a good idea. Made https://github.com/flathub/org.kde.gwenview/pull/169
