### ISSUE TITLE
Add kf5arcive, libavif, libheif, libjxl, and openexr for KImageFormats

### ISSUE THREAD

**Issue by alastortenebris** [flathub/org.kde.gwenview#30]
KImageFormats adds support for multiple image formats such as `psd`, `jxl`, and `avif`.

**Comment by travier** [comment]
https://invent.kde.org/packaging/flatpak-kde-runtime/-/merge_requests/90

**Comment by vulongm** [comment]
Looks like kf5arcive, libavif, libheif, libjxl, and openexr might have to be added to the manifest for the package or runtime as well for some of the additional formats to work with KimageFormats. https://invent.kde.org/frameworks/kimageformats/-/blob/master/CMakeLists.txt

**Comment by vulongm** [comment]
For some dependencies like libavif that might be a bit trickier as it requires rav1e and cargo-c which uses Rust SDK. Krita uploaded tarballs for those dependencies at https://files.kde.org/krita/build/dependencies/flatpak/ which allows for offline installation that can be used with flatpak-builder.

See https://github.com/flathub/org.kde.krita/blob/89ab5bdf5a581bd4709f63fec92e6b1fad551b0b/org.kde.krita.yaml#L721 for reference as well on the manifest.

**Comment by travier** [comment]
There is a script to generate manifest from Rust dependencies somewhere on Flathub so that you don't have to do as Krita does AFAIK.

**Comment by travier** [comment]
Clearing the assignee as I'm not actively working on this.

**Comment by travier** [comment]
jxl & libavif: https://invent.kde.org/packaging/flatpak-kde-runtime/-/commit/60ae78cb9556afa0d9cdea56200008c4d3f6ef7b

**Comment by Justinzobel** [comment]
MR for adding libheif here https://invent.kde.org/packaging/flatpak-kde-runtime/-/merge_requests/158

**Comment by travier** [comment]
Should be fixed with https://github.com/flathub/org.kde.gwenview/pull/164

**Comment by Justinzobel** [comment]
Can confirm all of these are now working.
